### PR TITLE
Update the README with there no longer being old versions in the docs

### PR DESCRIPTION
**Pull request by asmeurer**
This is a followup to https://github.com/sympy/sympy_doc/pull/33 which updates the stuff in the README now that we don't serve old versions of the docs. 

We will also need to update the release script in sympy to edit `releases.txt` correctly and to not save the old `latest` as the previous version. The new process is actually simpler, so this should not be hard.

### CODE REVIEW

**Comment by asmeurer** [comment]
I also pushed some updates to the sidebar. 

- Now says "Documentation version" instead of "Docs for other versions"
- Changed the releases text to "SymPy 1.5.1 (latest release)" and "SymPy 1.6.dev (development version)"
- Always show both versions on the page

Example

Screenshot 2020-01-31 17 42 20

Suggestions welcome

**Comment by oscarbenjamin** [comment]
> Example
> 
> 
> 
> Suggestions welcome

This link doesn't work

**Comment by oscarbenjamin** [comment]
> I also pushed some updates to the sidebar.
> 
> * Now says "Documentation version" instead of "Docs for other versions"
> * Changed the releases text to "SymPy 1.5.1 (latest release)" and "SymPy 1.6.dev (development version)"
> * Always show both versions on the page

That sounds like the right thing to do

**Comment by asmeurer** [comment]
I messed up the image upload. If you reload the page it will be there.

**Comment by oscarbenjamin** [comment]
I'm just cloning the repo which is enormous. Maybe it's worth compressing the history..

**Comment by oscarbenjamin** [comment]
It took a while to clone on my internet connection (2.6GB download).

This looks good though. It's better than my other suggestion.

**Comment by asmeurer** [comment]
Yeah, I was thinking maybe we should reset the history (and keep this history around in a separate repo in case we need it). 

I think the problem is the images that are checked in with every dev build are different each time. So we we should fix that somehow or it will continue to happen.

**Comment by oscarbenjamin** [comment]
I'm not sure that we need to worry about the history of this repo. Almost all changes are just derived from sympy/sympy.git. How about this:

1. Rename this repo to `sympy_doc_old_versions`
2. Create a new `sympy_doc`

In the new `sympy_doc` have a master branch and gh-pages and dev-doc branches. Meaningful changes to the code here (like this PR) go in to the master branch. The other branches always have just one extra commit that comes from adding the doc build directory from sympy/sympy.git. When releasing a new version (or rebuilding the dev docs) we just:

1. Unwind the top commit on gh-pages
2. Merge in master
3. Commit the new doc directory
4. Force push

Then we can have version control with history for the independent code in this repository. The other files which are derived from sympy/sympy.git are only stored once in the history.

**Comment by asmeurer** [comment]
I was using the history when doing this to see which versions I needed to push up redirects for. But it also wasn't easy because some git commands run really slowly on this repo.

**Pull request merged**
