### PR TITLE
Hotfix update to Mathjax url for new CDN

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Updates the Mathjax URL as discussed in [https://github.com/sympy/sympy/pull/15955](https://github.com/sympy/sympy/pull/15955)

These changes are automatically generated with this script (t.py)
```python
import sys

old = rb'<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full"></script>'
new = rb'<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_HTML-full"></script>/'

for filename in map(str.strip, sys.stdin):
    print(filename)
    with open(filename, 'rb') as fin:
        content = fin.read()
    content = content.replace(old, new)
    with open(filename, 'wb') as fout:
        fout.write(content)
```
and this command
```console
$ find . -name '*.html' | python t.py
```

I have skimmed through the changes but I can't honestly say that I looked at every part of the diff (I tried a few ways to do this efficiently but the diff is just too big). I've checked a few of the resulting html files and they have the correct new url and seem to render equations fine.

### CODE REVIEW

**Comment by asmeurer** [comment]
GitHub does not like this diff. 

If you've tested that it works, this can be merged.

**Comment by oscarbenjamin** [comment]
I've merged this change to the old docs. I'll check back on the docs to see that the link is changed and the equations still render...

**Comment by oscarbenjamin** [comment]
This is an example link to look at to see if the equations are rendering correctly:
[https://docs.sympy.org/1.2/modules/solvers/ode.html](https://docs.sympy.org/1.2/modules/solvers/ode.html)

**Comment by asmeurer** [comment]
Looks like it worked. Equations on that page render, and I confirmed in the web inspector that it's loading from the versioned URL.

**Comment by oscarbenjamin** [comment]
I've checked as well and can confirm that it seems okay (at least on that page - I'll check a bit more).

Worth noting that this change means that the old docs will always use the newest mathjax. The mathjax URL has a version in it but by using latest.js the version has no effect. There shouldn't be any need to further update this for new Mathjax versions but it's also possible that an update to Mathjax could break these docs.

**Comment by oscarbenjamin** [comment]
Okay I've checked a bunch of pages. I'm happy that this is done. Feel free to ping me if any problems emerge...

**Pull request merged**
