### PR TITLE
update index.html

### PR DESCRIPTION
**Pull request by Raghibshams456**
I have changed all update.html as needed hope this work!!

### CODE REVIEW

**Comment by asmeurer** [comment]
We will also need to remove the 1.6 and 1.6.1 directories (or replace them with redirects generated by the generate_redirects.py script).

**Comment by Raghibshams456** [comment]
Ok..I am doing as guided... thanks

**Comment by asmeurer** [comment]
Also, please don't open several pull requests. You can simply push changes to the branch for your existing pull request. I recommend using git locally rather than the GitHub web interface, as the latter will make it harder (and it will be impossible to generate redirects with it). See https://github.com/sympy/sympy/wiki/Development-workflow for information on how to use git. If you have issues, let us know and we can help.

**Comment by Raghibshams456** [comment]
Ok... actually I am new to open source ... thanks for guidance...I will learn quickly..

**Comment by Raghibshams456** [comment]
i have removed 1.6 and 1.6.1 directories ...but I am not able to create pull request..can anyone help please....
Screenshot from 2020-08-05 22-00-10

**Comment by Raghibshams456** [comment]
from past two days I am trying to solve this issue..

**Comment by asmeurer** [comment]
I'm not sure what you did, but you ended up creating a new commit history instead of commiting against the existing one. That's why it won't let you make a PR. You will likely need to start over. You should

- clone the repo
- Make a new branch (`git checkout -b fix`)
- Delete the 1.6 and 1.6.1 directories
- Make redirects to them using the generate_redirects script
- Do a `git commit --all` 
- Push up `fix`

**Pull request closed without merging**
