### PR TITLE
Update dev docs

### PR DESCRIPTION
**Pull request by debugger22**

### CODE REVIEW

**Comment by srjoglekar246** [comment]
Why doesn't this also include the recent changes made to the docs in physics.vector? Anything I am missing?

**Comment by asmeurer** [comment]
Indexes is a correct spelling. This breaks the SymPy release script.

**Comment by debugger22** [comment]
Ok, I'll revert it. But in readme it is mentioned `./generate_indices.py` so I changed it.

**Comment by debugger22** [comment]
Should I change the readme then?

**Comment by debugger22** [comment]
Changed the README instead.

**Comment by debugger22** [comment]
@srjoglekar246 Fixed that. @asmeurer We can merge it now.

**Comment by srjoglekar246** [comment]
Looks fine on my machine. Merging this.

**Comment by debugger22** [comment]
Thanks!

**Comment by asmeurer** [comment]
Yeah, I would just leave the spelling as is, so as not to break anything, and just fix the docs.

**Pull request merged**
