### PR TITLE
Remove old versions of the docs

### PR DESCRIPTION
**Pull request by asmeurer**
I also updated the sidebar text for the latest and dev docs a little bit. See the diffs for the individual commits.

I don't know if we should generate redirects for the old versions that were there so that links won't break (at least as long as they are to pages that still exist in latest). 

Note that if we merge this, the release script in sympy will need to be updated. 

See https://www.asmeurer.com/sympy_doc for what this will look like.

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
From the diffs I can see, I think you've decided to keep the current version and the development version. 

But how much time do we give to 1.4 docs before dropping it when the next version is released?
it cannot be dropped immdately as 1.5 is released. 

I suggest keeping 3 versions. The last, current, and the dev.
The last one will be removed when the dev version is released. 

So, after the 1.5 release, it will be: 
Last: 1.4
Current: 1.5
Dev: 1.6

After 1.6 release, it will be:
Last: 1.5
Current: 1.6
Dev: 1.7
and so on.

This, given our release schedule, gives it around 6 months which is more than enough for any user/project to shift to the new release of SymPy to not require the last version docs.

**Comment by certik** [comment]
Why not to keep the old docs around? Or is there some advantage of removing them?

**Comment by Sc0rpi0n101** [comment]
It is based on the discussion at 
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/sympy/5SWhrGTmZKw

Lots of google search results go to the old versions of the documentation instead of the latest ones, 
even going all the way back to 0.6.7

**Comment by asmeurer** [comment]
> Why not to keep the old docs around? Or is there some advantage of removing them?

What's even the advantage of having them? We don't actually support old versions. What ends up happening is that people find their way to old docs, either from Google (see the mailing list), or other. Old docs document the old API, so they are incorrect for anyone using the newest version. Some of the versions that we have are almost 10 years old. And what's even worse is that a bunch of people end up in mpmath docs, thinking it is SymPy, because we used to ship mpmath docs with SymPy docs. I've seen people confused by this in the wild a lot (StackOverflow, Gitter, issues on the issue tracker, etc.).

**Comment by asmeurer** [comment]
> I suggest keeping 3 versions. The last, current, and the dev.

Why? We don't actually support old versions. Once 1.5 is out, 1.4 will no longer be supported. I only see this confusing people more. And if we delete old versions, then people will end up with links that are broken (that's one thing I'm not sure about here, if we should do some kind of redirect or custom 404 for the pages that are removed). 

If people want the documentation for old versions, they can always download them from the [releases page](https://github.com/sympy/sympy/releases), which includes pre-built html and pdf docs for each release, or build them themselves from the sources that are included in the release tarball or from git. Or they can just look at the online help, since the majority of documentation is docstrings that are part of the source code.

In fact, it's even confusing in the state of things here, since there is still "latest" and "dev", but people end up on "dev" and don't realize that features aren't actually in the released version yet. So we should figure out how to add some kind of header to the dev docs.

**Comment by certik** [comment]
Thanks. That makes sense. I am fine to remove the old version, especially since we do not support it.

The only advantage of keeping it is that distributions like Debian or Ubuntu will have an older version of SymPy, and people still want to be able to read the documentation. As an example, if I use `cmake`, each system has a different version installed on it. If you go online: https://cmake.org/cmake/help/v3.16/, you can change the version that you are interested in --- they keep about last 10 or so versions online.

**Comment by asmeurer** [comment]
I've updated this. GitHub is having a hard time showing the updates here, so hopefully they will eventually show up. Otherwise we may need to merge this manually.

**Comment by asmeurer** [comment]
I pushed a build of this up to my fork so you can see what it will look like https://www.asmeurer.com/sympy_doc

**Comment by oscarbenjamin** [comment]
This looks good to me.

Do the notes for updating post-release need to be updated at all? (I'd suggest doing that in a follow up PR since the diff here makes it impossible to review anything).

**Comment by asmeurer** [comment]
Yeah. I forgot that there was stuff in the README here. Actually what really needs to be updated is the release script.

**Comment by asmeurer** [comment]
I'm going to merge this in 24-hours unless there are objections.

**Comment by certik** [comment]
It's fine with me.

**Comment by asmeurer** [comment]
OK, merging.

**Comment by asmeurer** [comment]
I went ahead and pushed up "latest" redirects for the old versions. They are based on the current version of the docs, so if anything has been moved around or will move around in the future it won't work. But that's as good as we are going to get unless someone wants to work harder to make better redirects here. In particular, any old hotlinks to the mpmath docs that we used to include in the SymPy docs will now just 404. Hopefully people can find their way to the real mpmath docs.

**Comment by oscarbenjamin** [comment]
I think this looks good but two points:

1. We should make sure that any instructions for managing this repo are up to date. Aside of updating the release script this repo should describe how it should be updated (how else can someone check the correctness of the release script?).

2. The "docs for other versions" heading in the sidebar should maybe have a different title.

**Comment by asmeurer** [comment]
I opened https://github.com/sympy/sympy_doc/pull/34 for point 1

For point 2, I agree, and I was just thinking about that. Any suggestions what it should say?

**Comment by oscarbenjamin** [comment]
> For point 2, I agree, and I was just thinking about that. Any suggestions what it should say?

I did think about that before deciding not to offer a suggestion :)

In the (new) current setup that heading is for a single link that is used to alternate between two possibilities. If the header has to be the same on both then perhaps it could say "Switch between release and dev docs".

**Pull request merged**
