### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Raghibshams456**
remove two version because I think that is extra ....as given issue there should be only two ...latest version and dev...

### CODE REVIEW

**Comment by Raghibshams456** [comment]
See https://docs.sympy.org/latest/index.html. We removed the older versions from the sidebar, but the most recent releases added them back. There should only be "latest" and "dev". The version number on "latest" is also wrong.

**Comment by asmeurer** [comment]
You should update releases.txt then run the generate_indexes.py script to update the index.html file.

**Comment by Raghibshams456** [comment]
Ok I will do that.... thanks

**Comment by Raghibshams456** [comment]
@asmeurer sir it is necessary to run generates_indexes.py script in my own system for updating to index.html file

**Comment by oscarbenjamin** [comment]
Yes, it should be run on your own system.

**Comment by Sc0rpi0n101** [comment]
Closing this as the changes have already been updated in #42

**Pull request closed without merging**
